
let options = {
    base: 550,
    width: 400,
    recovery_width: 360,
    counting_width: 100,
    counting_frame_width: 40,
    early_quistis: 'pingval',
    autofire_speed: 12,
    delay_frame: 285,
    ranks_order: "ulrd",
    strong_highlight_cards: [103, 105],
    highlight_cards: [21, 48, 53],
    order: 'reverse',
    console_fps: 60,
    game_fps: 60,
    player: 'zellmama',
    fuzzy: ['.', 'r', 'o', 'ro'],
    forced_incr: 10,
    accept_delay_frame: 3,
    prompt: "> ",
}